pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
               echo 'Simulando Deploying application...'
               // Aquí irían los comandos de despliegue
            }
        }
    }

    post {

        always {
            echo 'Siempre se ejecutara.'
        }

        success {
            echo 'La construcción, pruebas y despliegue se completaron con éxito.'
        }
        failure {
            echo 'Hubo un error en alguna etapa del pipeline.'
        }
        
    }

}